#!/usr/bin/env bash

function help {
  echo "Usage: config <zsh/nvim/tmux>"
  exit 1
}

function edit_commit_push {
  pushd "$1" || exit

  # Edit
  nvim

  # Commit
  if [ $# -ge 2 ]; then
    git commit -a -m "$2"
  else
    git commit -a
  fi

  # Push
  git push

  popd || exit
}

declare -A configs=(
  # ["zsh"]="$HOME/.zshrc"
  ["nvim"]="$HOME/.config/nvim/"
  ["tmux"]="$HOME/.config/tmux/"
)

if [ $# -eq 1 ] && [[ -v configs["$1"] ]]; then
  dir="${configs[$1]}"
  shift
  edit_commit_push "$dir" "$@"
else
  help
fi
