#!/usr/bin/env bash

show_help() {
  echo "Usage: ${0##*/} [PATTERN] [--help]"
  echo ""
  echo "Quickly select and connect to a Kubernetes pod with fuzzy finding."
  echo ""
  echo "Modes:"
  echo "  No arguments    - Interactive selection with fzf"
  echo "  With PATTERN    - Non-interactive filtered selection"
  echo "  --help          - Show this help message"
  echo ""
  echo "Examples:"
  echo "  ${0##*/}             # Interactive pod selection"
  echo "  ${0##*/} web         # Auto-select pod containing \"web\""
  echo "  ${0##*/} \"^auth-\"    # Regex match for pods starting with \"auth-\""
  echo "  ${0##*/} --help      # Show this help message"
}

FILTER=""

while [[ $# -gt 0 ]]; do
  case $1 in
  --help)
    show_help
    exit 0
    ;;
  *)
    if [ -n "$FILTER" ]; then
      FILTER="$1"
      shift
    else
      echo "Can not parse multiple filter values"
      exit 1
    fi
    ;;
  esac
done

if [ -n "$FILTER" ]; then
  selected=$(kubectl get pods --no-headers --all-namespaces=true | fzf --reverse --filter="$FILTER" --header="Select a pod to shell into")
else
  selected=$(kubectl get pods --no-headers --all-namespaces=true | fzf --select-1 --exit-0 --header="Select a pod to shell into")
fi

if [[ -n "$selected" ]]; then
  read -r namespace pod _ <<<"$selected"
  echo "Entering pod: $pod"
  kubectl -n "$namespace" exec -it "$pod" -- sh -c 'command -v bash >/dev/null && exec bash || exec sh'
else
  echo "No pod matching filter: '$FILTER'"
  exit 1
fi
